apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: kafka-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: connect
        image: confluentinc/cp-kafka-connect:6.2.0
        ports:
        - containerPort: 8083
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "connect"
        - name: CONNECT_GROUP_ID
          value: "connect-cluster"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "_connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "_connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "_connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/usr/share/confluent-hub-components"
        - name: CONNECT_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        volumeMounts:
        - name: connector-plugins
          mountPath: /usr/share/confluent-hub-components
        - name: config
          mountPath: /etc/kafka-connect
        - name: postgresql-jar
          mountPath: /usr/share/java/postgresql-42.2.23.jar
      volumes:
      - name: connector-plugins
        hostPath:
          path: /path/to/kafka-connect/connectors
      - name: config
        hostPath:
          path: /path/to/kafka-connect/config
      - name: postgresql-jar
        hostPath:
          path: /path/to/kafka-connect/postgresql-42.2.23.jar