version: '3.3'
services:
  database:
    image: 'postgres:16.2-alpine'
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      priv-aeroflot-pilot-net:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      priv-aeroflot-pilot-net:

networks:
  priv-aeroflot-pilot-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28  