version: '3.3'
services:
  database:
    image: 'postgres:16.2-alpine'
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      priv-aeroflot-pilot-net:
        ipv4_address: 172.16.254.3
    depends_on:
     - kafka
    #  - kafka-connect

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"

  kafka:
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092
    volumes:
      # - ./kafka/connect-plugins:/opt/kafka/connect-plugins
      - ./kafka/config:/opt/kafka/custom-config
      - ./kafka/logs:/var/lib/kafka/data
    environment:
      # KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      #       KAFKA_BROKER_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      priv-aeroflot-pilot-net:
        ipv4_address: 172.16.254.2
    depends_on:
      - zookeeper
  
  # kafka-connect:
  #   image: apache/kafka:3.7.0
  #   command: bash -c "/opt/kafka/bin/connect-standalone.sh /opt/kafka/config/connect-standalone.properties" 
  #   volumes:
  #     - ./kafka/connect-plugins:/opt/kafka/connect-plugins
  #     - ./kafka/connect-standalone.properties:/opt/kafka/config/connect-standalone.properties
  #     - ./kafka/connect-standalone-worker.properties:/opt/kafka/config/connect-standalone-worker.properties
  #   networks:
  #     priv-aeroflot-pilot-net:
  #       ipv4_address: 172.16.254.4
  #   depends_on:
  #     - kafka

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     priv-aeroflot-pilot-net:
  #       ipv4_address: 172.16.254.1

networks:
  priv-aeroflot-pilot-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28  